#
# DreamShell ISO Loader
# Network
# (c) 2009-2020 SWAT
#

include Makefile.cfg

TARGETCFLAGS += $(NET_CFLAGS)
LOBJECTS += $(NET)

# g2bus shall always be imported for the net loader
ifeq (,$(findstring g2bus.o,$(LOBJECTS)))
LOBJECTS += $(KOS_DIR)/src/g2bus.o
endif

NAME ?= net

all: $(BUILD)/$(NAME).bin

$(BUILD)/$(NAME).elf: $(OBJECTS)
	$(TARGETCC) $(TARGETCFLAGS) $(TARGETLDFLAGS) -o $@ $(OBJECTS) $(LIBS)
	$(TARGETSIZE) $@
